### ISSUE TITLE
use discord.py's scheduler

### ISSUE THREAD

**Issue by xjunko** [Zavents/discord#2]
https://github.com/Zavents/discord/blob/afa41dcbbcf4ae7e172159f4d522a75dd478b6a2/bot.py#L56-L62

dont do that dumbass, use the discord.py scheduler instead,

like this
https://github.com/xjunko/emotebot-priv/blob/main/moete/bot.py#L213-L219

**Comment by Zavents** [comment]
is this changing status of discord bot?

**Comment by Zavents** [comment]
mine is posting shit every 1 hour gap between that time

**Comment by xjunko** [comment]
> is this changing status of discord bot?

that doesnt matter, refer to the decorator.

> mine is posting shit every 1 hour gap between that time

yes, use the decorator, basically, on your on_ready state, fetch the channel then use that during trigger function

```py
async def on_ready(self) -> None:
    self.image_channel: discord.TextChannel = None

    if image_channel := await self.fetch_channel(CHANNEL_ID):
         self.image_channel = image_channel

    self._dumb_fucking_image_cycle.start()

@tasks.loop(minutes=60)
async def _dumb_fucking_image_cycle(self) -> None:
     if self.image_channel:
          await self.image_channel.send(random.choice(IMAGE_URLS))
```
